In [1]:
import torch
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [2]:
torch.tensor([[1,2,5],[3,4,3],[5,6,2]])

tensor([[1, 2, 5],
        [3, 4, 3],
        [5, 6, 2]])

In [3]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

[[1 2]
 [3 4]]


In [4]:
temp.shape

torch.Size([2, 2])

In [5]:
temp.view(4,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [6]:
temp.view(-1)

tensor([1, 2, 3, 4])

In [7]:
temp.view(1,-1)

tensor([[1, 2, 3, 4]])

In [8]:
temp.view(-1, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [9]:
and_data=torch.tensor([ [0,0],
                        [0,1],
                        [1,0],
                        [1,1] ], dtype=torch.float32)
and_labels=torch.tensor([ [0],
                          [0],
                          [0],
                          [1]], dtype=torch.float32)

In [10]:
import torch.nn as nn

In [11]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 1)
        self.sigmoid = nn.Sigmoid()
        #입력크기 2, 출력크기 1인 선형 레이어 정의함. 
        #self.fc2 = nn.Linear(2,1) 두번째 선형 레이어

    def forward(self, x): #forward - 입력받아서 출력 변환과정을 정의함
        x = self.fc1(x) #입력 x를 첫번째 선형레이어 fc1에 통과시킴. 선형변환 적용됨
        x = self.sigmoid(x) #그 결과에 시그모이드 함수로 변환하여, 0과 1 사이로 이진 확률로 해석나옴
        return x

In [12]:
l1 = nn.Linear(2,1)
x=l1(and_data)

In [13]:
x.shape

torch.Size([4, 1])

In [14]:
torch.relu(x)

tensor([[0.4932],
        [1.0405],
        [0.7822],
        [1.3295]], grad_fn=<ReluBackward0>)

In [15]:
l1.weight, l1.bias, l1.parameters

(Parameter containing:
 tensor([[0.2890, 0.5473]], requires_grad=True),
 Parameter containing:
 tensor([0.4932], requires_grad=True),
 <bound method Module.parameters of Linear(in_features=2, out_features=1, bias=True)>)

In [16]:
model = SimpleNN()
model

SimpleNN(
  (fc1): Linear(in_features=2, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [17]:
model(and_data)

tensor([[0.4366],
        [0.4488],
        [0.4690],
        [0.4814]], grad_fn=<SigmoidBackward0>)

In [18]:
loss_fn = nn.CrossEntropyLoss()

In [19]:
import torch.optim as optim
#weight 갱신, 천천히. 

In [20]:
model = SimpleNN()
loss_fn = nn.BCELoss() #loss 숫자로 보기 위해서 이걸로 바꿔봄
optimizer = optim.Adam(model.parameters(), lr=0.0001)

In [21]:
for epoch in range(10):
    optimizer.zero_grad() #경사 초기화
    outputs = model(and_data) #모델 예측
    loss = loss_fn(outputs, and_labels) #손실 계산
    print('loss', loss.cpu()) #손실 출력
    loss.backward()  #경사 계산
    optimizer.step() #모델 파라미터 업데이트 

#반복문을 다시 돌 때는 방정식의 weight. 가중치가 조금 바뀐 채로 그담번을 돌게 됨. 아주 조금
#가중치를 조금씩 조절해가면서 반복문을 돈다는거
#로스가 더이상 크게 유의미하게 줄지 않는 때까지 반복하면 됨

loss tensor(0.9015, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9015, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9014, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9013, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9013, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9012, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9011, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9010, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9010, grad_fn=<BinaryCrossEntropyBackward0>)
loss tensor(0.9009, grad_fn=<BinaryCrossEntropyBackward0>)


In [22]:
model(and_data)

tensor([[0.5928],
        [0.7299],
        [0.6934],
        [0.8076]], grad_fn=<SigmoidBackward0>)

In [23]:
def and_gate(x1, x2):
    return x1 and x2

In [24]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001)

for epoch in range(10):
    optimizer.zero_grad()
    outputs = model(and_data)
    loss = loss_fn(outputs, and_labels)
    print('loss', loss.cpu())
    loss.backward() 
    optimizer.step()

loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
loss tensor(-0., grad_fn=<DivBackward1>)
