In [1]:
import torch
import torch.nn as nn

In [2]:
#nn.Linear(2,1)
#nn.Sigmoid()
#nn.ReLU()
#nn.Softmax()
#nn.Dropout()

In [ ]:
#nn.Conv2d(1, 6, 3)
#nn.MaxPool2d(2,2)
#nn.Flatten()

In [4]:
X_train =torch.tensor([ [0,0],
                        [0,1],
                        [1,0],
                        [1,1.] ])

In [5]:
X_train.shape

torch.Size([4, 2])

In [6]:
X_train.dtype

torch.float32

In [11]:
y_label = torch.tensor([[0],
                        [0],
                        [0],
                        [1]])
#y_label = torch.tensor([0,0,0,1]) 데이터는 똑같은데 형식, shape이  다른 것의 차이를 보기 위해.

In [12]:
y_label.shape

torch.Size([4, 1])

In [22]:
linear = nn.Linear(4, 2)

In [16]:
x.shape

torch.Size([4, 1])

In [32]:
R_train=torch.rand(32, 3)

In [24]:
linear(R_train).shape

torch.Size([32, 2])

In [29]:
linear = nn.Linear(4, 2)
x = linear(R_train)
relu = nn.ReLU()
R = relu(x)
R

tensor([[0.0000, 0.0000],
        [0.0000, 0.1377],
        [0.0000, 0.0706],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0466],
        [0.1606, 0.1285],
        [0.0000, 0.0526],
        [0.0000, 0.1385],
        [0.0000, 0.0968],
        [0.0000, 0.0000],
        [0.0574, 0.2440],
        [0.0000, 0.1946],
        [0.0000, 0.0000],
        [0.0000, 0.0043],
        [0.1373, 0.0902],
        [0.0000, 0.0433],
        [0.2055, 0.0364],
        [0.0000, 0.0753],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0167, 0.2093],
        [0.0000, 0.1464],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.1576],
        [0.3548, 0.2871],
        [0.0000, 0.0000],
        [0.1190, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0908],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [37]:
linear2 = nn.Linear(3,2)
softmax = nn.Softmax()
dropout = nn.Dropout()
x = linear2(R_train)
dropout(x)
softmax(x)


tensor([[0.4080, 0.5920],
        [0.4753, 0.5247],
        [0.4855, 0.5145],
        [0.3276, 0.6724],
        [0.4848, 0.5152],
        [0.3839, 0.6161],
        [0.4142, 0.5858],
        [0.3925, 0.6075],
        [0.4468, 0.5532],
        [0.5519, 0.4481],
        [0.3576, 0.6424],
        [0.5055, 0.4945],
        [0.5862, 0.4138],
        [0.6003, 0.3997],
        [0.5216, 0.4784],
        [0.5736, 0.4264],
        [0.3604, 0.6396],
        [0.4327, 0.5673],
        [0.4739, 0.5261],
        [0.5230, 0.4770],
        [0.5331, 0.4669],
        [0.5541, 0.4459],
        [0.4787, 0.5213],
        [0.5118, 0.4882],
        [0.4047, 0.5953],
        [0.5740, 0.4260],
        [0.4602, 0.5398],
        [0.5215, 0.4785],
        [0.5569, 0.4431],
        [0.5007, 0.4993],
        [0.4655, 0.5345],
        [0.5424, 0.4576]], grad_fn=<SoftmaxBackward0>)

In [62]:
image = torch.rand(5, 16, 28, 28)
image.shape #(배치 크기, 입력 채널 수, 출력 데이터 높이와 너비)

torch.Size([5, 16, 28, 28])

In [56]:
conv = nn.Conv2d(6, 16, 3, padding='same') #(입력 채널 수=image.shape 했을때 채널 수와 동일, 출력 채널 수, 커널 크기=내가 원하는 만큼)

In [49]:
conv(image)

tensor([[[ 5.2259e-01,  5.7011e-01,  6.1152e-01,  ...,  3.7377e-01,
           2.2840e-01,  3.1282e-01],
         [ 3.6701e-01,  3.6092e-01,  3.7405e-01,  ...,  2.6429e-01,
           1.6829e-01,  1.0875e-01],
         [ 4.5435e-01,  3.7358e-01,  4.5336e-01,  ...,  5.0878e-01,
           4.3449e-01,  5.2996e-01],
         ...,
         [ 5.0732e-01,  4.4626e-01,  4.0709e-01,  ...,  4.8058e-01,
           4.4978e-01,  6.4186e-01],
         [ 4.0272e-01,  3.9226e-01,  2.1924e-01,  ...,  4.5805e-01,
           2.4843e-01,  1.5620e-01],
         [ 2.5766e-01,  2.2770e-01,  3.9023e-01,  ...,  4.6654e-01,
           6.0499e-01,  5.5423e-01]],

        [[ 3.1837e-01,  4.0152e-01,  4.2870e-01,  ...,  3.4439e-01,
           5.4009e-01,  1.7614e-01],
         [ 7.3140e-01,  7.9145e-01,  7.3035e-01,  ...,  5.6527e-01,
           7.0007e-01,  5.2336e-01],
         [ 9.7244e-01,  8.3188e-01,  5.4020e-01,  ...,  7.3930e-01,
           7.2195e-01,  6.4553e-01],
         ...,
         [ 6.0931e-01,  5

In [65]:
conv=nn.Conv2d(in_channels=16, out_channels=6, kernel_size=3, padding=1)
x = conv(image)
pool = nn.MaxPool2d(2) #2는 이미지 크기 2*2 즉 두칸씩 묶어서 망원경으로 최댓값을 뽑아내므로 이미지 크기가
x = pool(x)
x.shape

torch.Size([5, 6, 14, 14])

In [66]:
batch_size = 64

In [67]:
50000/batch_size

781.25

In [73]:
image = torch.rand(batch_size, 1, 28, 28)
image.shape #흑백이미지(1)가 64장 있다는 뜻 

torch.Size([64, 1, 28, 28])

In [69]:
conv = nn.Conv2d(1, 6, 3, padding='same')
x = conv(image)
pool = nn.MaxPool2d(2)
x = pool(x)
x.shape

torch.Size([64, 6, 14, 14])

In [72]:
flatten = nn.Flatten() #일렬로 평탄화, 64라는 배치 크기는 그대로 유지하면서 6*14*14 도출
x = flatten(x) #원래 (배치 크기, 채널 수, 높이, 너비) 였던 걸
x.shape #[배치 크기, 특성 수]로 변경하면 선형 레이어에 전달하기 쉬워짐

torch.Size([64, 1176])

In [74]:
i = torch.rand(30, 3, 10, 10)
i.shape #30장 배치짜리, rgb 3채널, 높이 너비는 10씩

torch.Size([30, 3, 10, 10])

In [77]:
conv = nn.Conv2d(3, 5, 5, padding='same') #3개 채널을 5개 채널로, 커널사이즈 5로 출력하라
x = conv(i)
pool = nn.MaxPool2d(3) #내가 볼 망원경 크기가 3*3이라고 
x = pool(x)
x.shape #배치크기 그대로, 출력채널수 5, 높이 너비 5씩

torch.Size([30, 5, 5, 5])

In [78]:
x = flatten(x)
x.shape

torch.Size([30, 125])